[package]
name = "oplus"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde", "clock"] }
bevy_ecs_ldtk = "0.13"